services:
  - type: web
    name: cek-pmi-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: TELEGRAM_TOKEN
        scope: build
        sync: false
      - key: PORT
        value: 10000

    # Auto-restart jika crash
    maxShutdownDelay: 30

    # Healthcheck
    healthCheckPath: /health
